baseURL = "https://blog.wangyx.com/navs/"
languageCode = "zh-CN"
title = "网址导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "wangyx"
  description = "website nav"
[params.search]
  enable = true
[params.darkmode]
  enable = true